// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CartItem(props) {
  var item = props.item;
  return JsxRuntime.jsx("table", {
              children: JsxRuntime.jsxs("tr", {
                    children: [
                      JsxRuntime.jsx("td", {
                            children: item.product_name
                          }),
                      JsxRuntime.jsx("td", {
                            children: item.qty.toString()
                          }),
                      JsxRuntime.jsx("td", {
                            children: item.price.toString()
                          }),
                      JsxRuntime.jsx("td", {
                            children: item.subtotal.toString()
                          })
                    ]
                  })
            });
}

var make = CartItem;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
